
export const TextData = {
    Empowering_text: `Empowering the Next Generation of Space Explorers!`,
    Discover_text: `Discover the science behind space exploration,from the principles of rocket propulsion to the latest technologies used in space missions.`,
    Food_text: `Explore the innovative techniques and nutritional considerations essential for sustenance beyond Earth's atmosphere.`,
    Biotechnology_text: `Explore the frontiers of life science in space with our Space Biotechnology & Astrobiology program! `,
    WhyChooseHeading: `Why Choose SpaceSkool?`,
    Expert_Instructors: `Learn from experienced instructors who bring a wealth of knowledge and experience to every class, ensuring a depth of understanding and inspiration in every subject.`,
    Innovative_Curriculum: `We offer cutting-edge curriculum designed to engage and inspire students, incorporating the latest advancements in space exploration and technology.`,
    Commitment_to_Excellence: `We're committed to excellence in education, continuously striving to enhance our programs and provide the best possible learning experiences for our students.`,
    Our_jerney_heading: `Join Our Community of Space Explorers!`,
    Our_jerney_paragraph: `Become a part of our community of space enthusiasts and industry professionals, and gain access to a wide range of networking opportunities, resources, and support.`,
    SpaceSkool_Description: `SpaceSkool is a brand owned and steered by ASTRO School of Space Education & Research Pvt Ltd established to focus on offering future-ready courses on Space Engineering to university students in India. We believe Space Technology is the future. And we are contributing to the Indian space industry by delivering skilled force to build the future.`,
    Links: ['Privacy Policy', 'Terms & Conditions ', 'Disclaimer', 'Cancellation & Refund Policy', 'Holiday Policy & List of Holidays', 'Website Terms & Conditions ',
        'Plagiarism and copyrights Policy', 'Data Storage Disclosure', 'Trademarks and other IPs', 'Company legalities',
        ' Home',
        'About',
        'SpaceKiddo Course',
        'Space Law Course',
        'Space Food Internship Program',
        'Learn building a drone',
        'Agricultural Spraying',
        'Aerial Mapping',
        'Laser Scanning',
        'Thermal Inspections & Mapping',
        'Drone / Aerial Survey',
        'Aerial Pipeline Monitoring',
        'Aerial Gas monitoring'],
    FooterText: '© 2022 by SpaceSkool | All rights reserved.\n SpaceSkool is a registered brand of ASTRO school of Space Education & Research Private Limited',
    Our_Vision_Text: 'We believe Space is not just for a very limited branches of Science and technology. We believe Space is for everyone, we meant for every domain. And we also believe all the science & technological advancements happening around the globe are to make/take a human life to an advanced level or make it more comfortable. And the same when we send humans to Space or on to any celestial bodies, every branch of science & technology is required to keep the astronaut safe and comfortable.',
    Our_Vision_SubHeading: `So that’s the vision for us, Space Education – For everyone and anyone.\nMaking Space Education accessible for everyone!!`,
    Our_Mission_Text: `At SpaceSkool, our mission is to ignite curiosity and fuel innovation by creating a dynamic learning environment where students are encouraged to explore, experiment, and engage with the wonders of space. Through hands-on research and practical experiences, we make space education both fun and meaningful, inspiring young minds to pursue space research and discovery. We believe that space is vital for all of humanity, and we are committed to raising awareness and fostering a deeper understanding of its significance for our future.`,
    Our_Mission_SubHeading: `We believe in the power of space to shape humanity’s future, and we’re committed to making its knowledge accessible to all.`,
    About_Us_Text: `At SpaceSkool, we believe that the future of exploration lies in the hands of curious, young minds. Our mission is to inspire and educate students about the wonders of space, empowering them to imagine beyond the Earth and into the vast cosmos. Through interactive learning, hands-on experiments, and expert-led sessions, we bring the universe closer to students from 6th to 10th grade, sparking their interest in astronomy, astrophysics, model rocketry, and stargazing.\n\nFounded on the vision to bridge the gap between conventional education and space science, SpaceSkool offers a range of specialized courses designed to make space education accessible, engaging, and practical. Our curriculum is crafted by leading educators and space professionals, ensuring a blend of foundational knowledge and real-world applications.`,
    Our_Specializations_Text: `We are majorly focused into various domains such Astronomy, Cosmology, Space Foods, Space Law and Space Engineering and much more.`,
    Rocket_text: `Assemble and launch your own model rockets while learning about basics of rocketry, propulsion, aerodynamics, & the physics of space flight!`,
    CubeSats_Text: `Explore satellite technology, learn about orbital mechanics, build and launch your own cubesats using our DIY kits and analyse the data .`,
    Stargazing_Text: `Identify celestial objects, use professional telescopes, and learn astrophotography techniques during our evening observation sessions.`,
space_Text:`Learn Space Sciences and it's vast domains such as astronomy, astrobiology, life in space, International Space Station and Space Missions from experts.`,
}
